### ISSUE TITLE
Sync collection not working - Kodi Matrix 19.1

### ISSUE THREAD

**Issue by Stele77** [razzeee/script.trakt#552]
## Expected Behavior
Manual Collection sync should work and sync all to Trakt.

## Current Behavior
Progress bar is stuck right at the very start, no progress at all. Confirmed after running for hours with no change and through log.

## Context
I tried re setup of addon, re auth, re setup of whole of Kodi, installing Kodi on my laptop in addition to my HTPC with the same result.

## Your Environment
Kodi Matrix 19.1
Latest Trakt Plugin from official matrix repo
Manual install, not Windows Store
Windows 10 20H2 64 Bit Professional
Intel Pentium 10th gen 2C/4T
16GB DDR4 RAM
120GB SSD

## Alternative system for testing:
Kodi Matrix 19.1
Latest Trakt Plugin from official matrix repo
Manual install, not Windows Store
Lenovo Thinkpad T480 (2018/2019)
Windows 10 20H2 Pro
24GB DDR4 RAM
256GB SSD

Log file is attached.
[kodi.log](https://github.com/trakt/script.trakt/files/6556651/kodi.log)

**Comment by bafflermeal2** [comment]
I have a similar issue on similar software/hardware, my trakt sync gets stuck on “movie(s) playcount will be updated in Kodi”.  If I uncheck this feature in trakt settings the remaining sync operations complete successfully.  Maybe uncheck certain settings in Trakt addon and see if it still gets stuck, at least it will narrow down what part of the sync process is failing.

**Comment by Stele77** [comment]
> I have a similar issue on similar software/hardware, my trakt sync gets stuck on “movie(s) playcount will be updated in Kodi”. If I uncheck this feature in trakt settings the remaining sync operations complete successfully. Maybe uncheck certain settings in Trakt addon and see if it still gets stuck, at least it will narrow down what part of the sync process is failing.

Thanks for your help, sadly even with all options disabled it get stuck right at the very start with "loading movies from Kodi" ("Lade filme aus Kodi" in German). 
Which seems to confirm what i as a total programming noob seem to understand from the log file. It seems to query the Kodi database and then somehow fails i guess, though i may be absolutely wrong about that. 
Tried every imaginable combination to triangulate the problem; without input from a dev who knows how to analyze the attached log file i dont know what else to try..

**Comment by razzeee** [comment]
Your log shows this error, which seems windows specific and points to something about the timezone/time https://github.com/dateutil/dateutil/issues/197

**Comment by Stele77** [comment]
> Your log shows this error, which seems windows specific and points to something about the timezone/time [dateutil/dateutil#197](https://github.com/dateutil/dateutil/issues/197)

Thanks Razzeee for looking into this, just checked that issue you linked. Seems i am screwed if i am reading this right, as it still is not fixed upstream..
I tried to change my Windows time zone and locale to UK and settings in Kodi too to maybe having a work around, sadly this did not work either. 
The linked issue mentioned downgrading dateutil with pip to version 2.53. But how can i do that on windows? I only use Windows for my HTPC so i can also game on it, all my other workstations and servers are running linux and have no clue how to do that or how Python/PIP is packaged and related to with Kodi on Windows.
And how can i be the only Windows 10+UTC+1 Kodi+trakt user that has these problems, there must be millions? 
Maybe going back to Leia would be the only solution here for someone with my skillset at least. Which i would really like to avoid now that i migrated my whole setup over many long hours and days.
Thanks again for taking the time to look into this; Knowing this is an upstream bug and not some error on my end does help already.
If someone has come up with a fix or workaround, please post, i will keep my matrix setup as backup so i can test any fixes if they come up.

**Comment by Stele77** [comment]
> Your log shows this error, which seems windows specific and points to something about the timezone/time [dateutil/dateutil#197](https://github.com/dateutil/dateutil/issues/197)

Thanks Razzeee for looking into this, just checked that issue you linked. Seems i am screwed if i am reading this right, as it still is not fixed upstream..
I tried to change my Windows time zone and locale to UK and settings in Kodi too to maybe having a work around, sadly this did not work either. 
The linked issue mentioned downgrading dateutil with pip to version 2.53. But how can i do that on windows? I only use Windows for my HTPC so i can also game on it, all my other workstations and servers are running linux and have no clue how to do that or how Python/PIP is packaged and related to with Kodi on Windows.
And how can i be the only Windows 10+UTC+1 Kodi+trakt user that has these problems, there must be millions? 
Maybe going back to Leia would be the only solution here for someone with my skillset at least. Which i would really like to avoid now that i migrated my whole setup over many long hours and days.
Thanks again for taking the time to look into this; Knowing this is an upstream bug and not some error on my end does help already.
If someone has come up with a fix or workaround, please post, i will keep my matrix setup backuped so i can test any fixes if they come up.

**Comment by razzeee** [comment]
I think I've seen someone in the kodi forum with the same problem, not sure what else might be causing this, but it seems to only happen to a few people. I'm not sure if you can safely downgrade the version, it might be possible by hand, but cause problems.

You might be able to download https://github.com/Razzeee/script.module.dateutil/tree/b37d88c31a243a7d8347f115a8725bc7d6c7e660 and just replace the one you are using right now with that one.

**Comment by bafflermeal2** [comment]
Based on what was said here I was able to solve my trakt sync issues.  I went to windows time zone settings and changed my time zone from “ (UTC-08:00) Pacific Time (US & Canada) ” to “ UTC-08:00) Coordinated Universal Time-08 ”.  Trakt was able to sync completely right away.  I tested this on both my problem machines with success.  Apparently time is a flat circle.

**Comment by Stele77** [comment]
> Based on what was said here I was able to solve my trakt sync issues. I went to windows time zone settings and changed my time zone from “ (UTC-08:00) Pacific Time (US & Canada) ” to “ UTC-08:00) Coordinated Universal Time-08 ”. Trakt was able to sync completely right away. I tested this on both my problem machines with success. Apparently time is a flat circle.

WOW THANK YOU! I just tried multiple different options for my time zone, and South Africa worked.. ;) 
Flat circle indeed! :)

Will leave this issue open until a real upstream fix will arrive!

**Comment by Stele77** [comment]
> I think I've seen someone in the kodi forum with the same problem, not sure what else might be causing this, but it seems to only happen to a few people. I'm not sure if you can safely downgrade the version, it might be possible by hand, but cause problems.
> 
> You might be able to download https://github.com/Razzeee/script.module.dateutil/tree/b37d88c31a243a7d8347f115a8725bc7d6c7e660 and just replace the one you are using right now with that one.

Thanks, the workaround bafflermeal2 posted indeed works, will leave the issue open for others with the problem to find a workaround until an upstream fix is coming.
Thanks again!

**Comment by Psymann** [comment]
I am also having this issue, using matrix or Leia on win 10, in the uk. Both windows machines add to Trakt when watched, but neither sync anymore. In fact the only sync that does work is via tiny media manager and that only adds to collection, not removes deleted. Additional error, after triggering trakt add on, kodi hangs, cant safely shut it down, the close/wait for program to respond dialogue appears every time.

**Comment by rantanlan** [comment]
same for me on W10 in de. If i chance the timezone to something different it starts, but fails in between.
If I could provide any more information to get this fixed? Downgrading the dateutil isn't working on windows imho, its incompatible anyway since it relys on python 2 imho.

**Comment by droopified** [comment]
Its not working for me either but everything else works. After watching a movie it marks it on trakt as watched. I use external scraper on windows which syncs to Kodi and adds the movie to the library and it used to work fine but not anymore. I use trakt a lot and it's an important feature for me!

**Comment by razzeee** [comment]
So does changing the timezone help for you? Can you send logfiles?

**Comment by droopified** [comment]
the timezone wasnt an issue for me but after messing with the addon and seeing the logfiles in debug mode for the addon and the kodi log, the way i fixed the collection sync issue was to go into the addon settings for trakt and change the startup delay to at least 1. im not sure if this is seconds or minutes but either way after changing this value to 5, rebooted and waiting 5 minutes, added a new movie and it finally synced to the trakt site. it wasnt instant tho so after adding the movie to the library and even after you see the notification, give the trakt site a few minutes to update. after seeing that worked i just changed the delay to the value of 1 and rebooted again and added a movie. it continued to work! edit: FWIW the first time i changed the startup delay, it actually marked all the missed synced movies from the last manual run and marked all the new movies since then as collected.

**Comment by drvid** [comment]
I'm having this same problem, and I am not sure of how to work around. I have tried all UTC-5:00 options in my Windows and the script still won't sync. Here is my log file...
https://paste.kodi.tv/buhamajiwi.kodi
Really despirate for a solution so I can retain my watched movie data in Trakt.
